import type { TranslationStructure } from './types';

export const translations: TranslationStructure = {
    // Navigation
    nav: {
        login: 'Login',
        register: 'Register',
        dashboard: 'Dashboard',
        logout: 'Logout',
    },
    // Hero Section
    hero: {
        title: 'Master New Vocabulary with Ease',
        subtitle:
            'Save words, learn with flashcards, and get AI-powered examples. Your personalized vocabulary learning journey starts here.',
        cta: 'Get Started for Free',
    },
    // Features Section
    features: {
        title: 'Why Choose EasyWords?',
        subtitle: 'Everything you need to build your vocabulary efficiently',
        items: {
            flashcards: {
                title: 'Smart Flashcards',
                description:
                    'Study with interactive flip cards that help you memorize words through active recall. Track your progress and focus on words that need more practice.',
            },
            aiExamples: {
                title: 'AI-Powered Examples',
                description:
                    'Get context-aware usage examples generated by AI. Understand how words are used in real-life situations and learn proper usage.',
            },
            multiPlatform: {
                title: 'Multi-Platform Access',
                description:
                    'Access your vocabulary anywhere, anytime. Seamlessly sync between web and mobile applications for uninterrupted learning.',
            },
            statistics: {
                title: 'Progress Tracking',
                description:
                    "Monitor your learning journey with detailed statistics. See how many words you've learned, your streak, and areas for improvement.",
            },
        },
    },
    // Screenshots Section
    screenshots: {
        title: 'See EasyWords in Action',
        subtitle: 'Discover how our platform helps you learn effectively',
    },
    // Footer
    footer: {
        tagline: 'Build your vocabulary, one word at a time.',
        rights: 'All rights reserved.',
    },
    // Words
    words: {
        page_title: 'Add Word',
        page_description: 'Fill the form to add a new word to your vocabulary',
        add_new_word: 'Add New Word',
        original_label: 'Original Word',
        original_placeholder: 'Enter word',
        translated_label: 'Translation',
        translated_placeholder: 'Enter translation or use AI',
        language_label: 'Language',
        language_placeholder: 'Select language',
        ai_translate: 'AI',
        translating: 'Translating...',
        save_word: 'Save Word',
        saving: 'Saving...',
        cancel: 'Cancel',
        go_to_word: 'Go to Card',
        add_another: 'Add Another Word',
        success_title: 'Word Created Successfully!',
        success_description: 'ID:',
        word_exists:
            'This word already exists in your vocabulary for the selected language.',
        translation_error: 'Failed to get translation. Please try again.',
    },
    // Auth
    auth: {
        login: {
            title: 'Log in to your account',
            description: 'Enter your email and password below to log in',
            email: 'Email address',
            email_placeholder: 'email@example.com',
            password: 'Password',
            password_placeholder: 'Password',
            remember_me: 'Remember me',
            submit: 'Log in',
            forgot_password: 'Forgot password?',
            no_account: "Don't have an account?",
            sign_up: 'Sign up',
        },
        forgot_password: {
            title: 'Forgot password',
            description: 'Enter your email to receive a password reset link',
            email: 'Email address',
            email_placeholder: 'email@example.com',
            submit: 'Send password reset link',
            return_to_login: 'Or, return to',
            log_in: 'log in',
        },
        reset_password: {
            title: 'Reset password',
            description: 'Enter your new password below',
            password: 'New password',
            password_placeholder: 'New password',
            password_confirmation: 'Confirm password',
            password_confirmation_placeholder: 'Confirm password',
            submit: 'Reset password',
        },
        register: {
            title: 'Create an account',
            description: 'Enter your details below to create your account',
            name: 'Full name',
            name_placeholder: 'John Doe',
            email: 'Email address',
            email_placeholder: 'email@example.com',
            password: 'Password',
            password_placeholder: 'Password',
            password_confirmation: 'Confirm password',
            password_confirmation_placeholder: 'Confirm password',
            submit: 'Create account',
            has_account: 'Already have an account?',
            log_in: 'Log in',
        },
        verify_email: {
            title: 'Verify email',
            description:
                'Please click the button below to verify your email address',
            submit: 'Verify email',
            resend: 'Resend verification email',
        },
        common: {
            or: 'or',
            back: 'Back',
            next: 'Next',
            cancel: 'Cancel',
            save: 'Save',
            delete: 'Delete',
            edit: 'Edit',
            loading: 'Loading...',
            success: 'Success',
            error: 'Error',
            required: 'This field is required',
            invalid_email: 'Please enter a valid email address',
            password_min_length: 'Password must be at least 8 characters',
            password_mismatch: 'Passwords do not match',
        },
    },
} as const;
