import type { TranslationStructure } from './types';

export const translations: TranslationStructure = {
    // Navigation
    nav: {
        login: 'Log in',
        register: 'Register',
        dashboard: 'Dashboard',
    },
    // Hero Section
    hero: {
        title: 'Master New Vocabulary with Ease',
        subtitle:
            'Save words, learn with flashcards, and get AI-powered examples. Your personalized vocabulary learning journey starts here.',
        cta: 'Get Started for Free',
    },
    // Features Section
    features: {
        title: 'Why Choose EasyWords?',
        subtitle: 'Everything you need to build your vocabulary efficiently',
        items: {
            flashcards: {
                title: 'Smart Flashcards',
                description:
                    'Study with interactive flip cards that help you memorize words through active recall. Track your progress and focus on words that need more practice.',
            },
            aiExamples: {
                title: 'AI-Powered Examples',
                description:
                    'Get context-aware usage examples generated by AI. Understand how words are used in real-life situations and learn proper usage.',
            },
            multiPlatform: {
                title: 'Multi-Platform Access',
                description:
                    'Access your vocabulary anywhere, anytime. Seamlessly sync between web and mobile applications for uninterrupted learning.',
            },
            statistics: {
                title: 'Progress Tracking',
                description:
                    "Monitor your learning journey with detailed statistics. See how many words you've learned, your streak, and areas for improvement.",
            },
        },
    },
    // Screenshots Section
    screenshots: {
        title: 'See EasyWords in Action',
        subtitle: 'Discover how our platform helps you learn effectively',
    },
    // Footer
    footer: {
        tagline: 'Build your vocabulary, one word at a time.',
        rights: 'All rights reserved.',
    },
} as const;
